select * from fact
select * from Location
select* from Product 


--1. Display the number of states present in the LocationTable. 
select count(Distinct(State)) as No_of_States
from Location

--2. How many products are of regular type?
select count(ProductId) as PR_Type from Product
where Type='Regular'

--3. How much spending has been done on marketing of product ID 1?
select sum(Marketing) as total_Mr from fact
where ProductId=1

--4. What is the minimum sales of a product?
select min(Sales) as Min_sale
from fact

--5. Display the max Cost of Good Sold (COGS).
select max(COGS) as max_cogs from fact

--6. Display the details of the product where product type is coffee. 
select * from product
where Product_Type='Coffee';

--7. Display the details where total expenses are greater than 40. 
select * from fact
where Total_Expenses>40;

--8. What is the average sales in area code 719?
select Avg(Sales) from fact
where Area_Code=719;

--9. Find out the total profit generated by Colorado state.
select sum(f.Profit) as Colarado_profit from fact f join Location L
on (f.Area_Code=L.Area_Code) 
where State='Colorado';

--10. Display the average inventory 
select productId, avg(Inventory) as Avg_inventory from Fact group by ProductId


--11.Display state in a sequential order in a Location Table. 
 select State from Location
 order by State Asc;

 --12.Display the average budget of the Product where the average budget
--margin should be greater than 100.
select avg(Budget_Margin) as Product_budget from fact 
where Budget_margin>100;

--13. What is the total sales done on date 2010-01-01?
select sum(Sales) as total_sales from fact
where Date='2010-01-01';

--14. Display the average total expense of each product ID on an individual date.
select ProductId, Date, AVG(Total_Expenses) AS average_total_expense
from fact
GROUP BY ProductId,Date;

--15.. Display the table with the following attributes such as date, productID, product_type, 
--product, sales, profit, state, area_code

select f.date,f.ProductId, f.Profit,P.Product, f.Sales, P.Product_Type,l.State,l.Market,l.Area_Code
from fact f join Product P
on (f.ProductId=P.ProductId)
join  Location l
on (f.Area_code=l.Area_code)

--16. Display the rank without any gap to show the sales wise rank.

select Sales,
Dense_Rank() over( order By Sales Asc) DR
from fact

--17. Find the state wise profit and sales
select State,
sum(Profit)as PR,sum(Sales) as s
from fact f inner join Location l on
(f.Area_code=l.Area_code)
group by State;

--18. Find the state wise profit and sales along with the productname.
select l.State,p.Product_Type,
sum(Profit)as Pr,Sum(Sales) as S
from fact f join Product p
on (f.ProductId=p.ProductId)
inner join Location l
on (l.Area_Code=f.Area_Code)
group by l.State,p.Product_Type;

--19. If there is an increase in sales of 5%, calculate the increased sales
select Sales,
Sales*1.05 as Increase_sales
from fact;

--20. Find the maximum profit along with the product ID and producttype.
select f.ProductId,p.Product_type,max(Profit) as PR_Profit
from fact f join Product p
on (f.ProductId=p.ProductId)
group by f.ProductId,Product_Type;


--21. Create a stored procedure to fetch the result according to the product typefrom Product Table.
create or alter procedure Productlist
as begin
select Product_Type from Product 
where ProductId=1;
end
execute Productlist;




--22. Write a query by creating a condition in which if the total expenses is lessthan60 then it
--is a profit or else loss.
select Total_Expenses,
case
when Total_Expenses < 60
then 'Profit'
else 'Loss'
end as Profit_loss
from fact


--23. Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the
--data in hierarchical order.
select Date, ProductId, sum(Sales) as Weekly_sales from fact 
group by rollup (Date,ProductId)

--24. Apply union and intersection operator on the tables which consist of
--attribute area code.
select Area_Code from fact
union
select Area_code from Location

select Area_Code from fact
intersect
select Area_code from Location


--25. Create a user-defined function for the product table to fetch a particular
--product type based upon the user’s preference.
create function GetProductType
(@Product_Type varchar(50))
returns Table
as 
return
(
select ProductId, Product_Type,Product, Type from Product
where Product_Type=@Product_Type);

select * from dbo.GetProductType('Espresso');

--26. Change the product type from coffee to tea where product IDis 1 andundoit.
update Product
set Product_Type ='Tea'
where ProductId=1;

--27. Display the date, product ID and sales where total expenses are
--between 100 to 200.
select Date,ProductId,Sales,Total_Expenses from fact
where Total_Expenses between 100 and 200;


--28. Delete the records in the Product Table for regular type.
delete Product
where Type='Regular';

select * from product
begin transaction
delete Product
where Type='Regular';
rollback


--29. Display the ASCII value of the fifth character from the columnProduct.
select ASCII(substring(Product,5,1)) As Fifth_char_ascii from Product